version: '3'
services:
  db:
    image: 'postgres:12'
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
